## The root URL of the API service, provided by taalapi
## https://github.com/ThePib/taalapi
apiUrl: https://taalapi.example.org

## Command prefix
## A small identifier, usually and preferrably a single character
## that is used to invoke the bot.
commandPrefix: ""

## ID of the Discord guild (server) this bot instance runs on
## This is used at various points in the code, to make sure that
## messages get delivered to the right destination.
guildId: ""

## Channel to send log messages to. Must be a text channel.
## Leave empty to disable the feature.
logChannel: ""
